name: deploy

on:
  push:
    branches:
      - main

jobs:
  push-image-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: oss-ava
          heroku_email: caleblemoine@gmail.com
          usedocker: true
