name: publish

on:
  push:
    branches:
      - main

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ava
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:latest
